### ISSUE TITLE
Chaining setters?

### ISSUE THREAD

**Issue by mdboom** [Hoverbear/getset#1]
Very new to rust, and think this library is really cool.

I wonder if it would be possible to have setters return a reference to self, such that you could chain setters, e.g.:

```
obj
   .set_foo(2)
   .set_bar(3);
```

**Comment by Hoverbear** [comment]
I think this would be possible!

We'd have to modify https://github.com/Hoverbear/getset/blob/master/src/setters.rs#L28 and https://github.com/Hoverbear/getset/blob/master/src/setters.rs#L38.

**Comment by Boscop** [comment]
Btw, I use `getset` a lot in combination with `delegatemethod` and have issues with leaked `&mut Self` access to members which I don't want:
https://github.com/crlf0710/delegatemethod-rs/issues/6

I'd prefer if there was a way to turn off the chainability (returning `&mut Self`) in the attribute when specifying the setters. Or if chaining wasn't even the default but could be enabled in that attrib with e.g. `#[set = "."]`/`#[set = ".pub"]` (I never use chaining anyway).

**Comment by Hoverbear** [comment]
@Boscop Hi! That sounds like a very valid feature. How about `#[set = "chain pub"]`? I would be happy to accept a pr for that!
