### ISSUE TITLE
primitive types support

### ISSUE THREAD

**Issue by Dushistov** [Hoverbear/getset#10]
It would be convenient,
if for types [ui][8|16|32|64|128], usize, isize, f32,f64,bool
`getset` will be generat getters that return value, not reference,
example:

```Rust
#[derive(Debug, Default, Clone, Getters, Setters)]
struct Foo {
    #[get]
    #[set]
    x: f64,
}
fn f() {
    let mut f = Foo::default();
    f.set_x(1.5);
    let x: f64 = f.x();
}
```

**Comment by Boscop** [comment]
Yes! I've been advocating for this, too!

**Comment by Dushistov** [comment]
@Boscop I implemented this feature, looks forward for review

**Comment by Hoverbear** [comment]
Related to #12, #3.

**Comment by KizzyCode** [comment]
It's probably the best to implement this for all copy types (if this is possible)

**Comment by Dushistov** [comment]
> Yeah, It's probably the best to implement this for all copy types (if this is possible)

Currently it is impossible, this need something like negative trait bounds to distinguish between types that impl Copy and not.

**Comment by Hoverbear** [comment]
See #29
