### ISSUE TITLE
Add Boscop as maintainer

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/getset#17]
@boscop, I sent you an invite to join as a maintainer. Feel free to add your name to the crate metadata. :joy: You seem to care and have a vested interest in this, so I value your opinion on the future direction. I don't have your contact details so I resorted to this. :)

If you accept please add yourself to the crate metadata. I can add you to the crates.io project if you'd like to publish as well.

**Comment by Boscop** [comment]
Thanks! I'm a little busy this week but I'll have more time soon..
