### ISSUE TITLE
Annotating structs with #[get] or #[set] should propagate to all fields.

### ISSUE THREAD

**Issue by tylerhawkes** [Hoverbear/getset#21]
This is a really useful library that I've been using quite a bit. Most of the time I want all struct fields to be `#[get = "pub"]` so being able to annotate a struct would be quite useful. I've come from the [Java](https://projectlombok.org/features/GetterSetter) world where this can be done and there are also negating annotations that prevent getters and setters from being generated or made public, so some syntax like that may be useful.

**Comment by Hoverbear** [comment]
I think that's a reasonable and unobtrusive feature request. :) I unfortunately don't have the bandwidth to do this at the moment, but someone is welcome to pick it up!

**Comment by akineralkan** [comment]
There is similar question asked in the stackoverflow. 
I think it may help the implementation for this issue.
Here is the [link](https://stackoverflow.com/questions/53866508/how-to-make-a-public-struct-where-all-fields-are-public-without-repeating-pub/53869723#53869723)

**Comment by Hoverbear** [comment]
Closed by https://github.com/Hoverbear/getset/pull/24
