### ISSUE TITLE
Can we have an option to prefix it with `get_`?

### ISSUE THREAD

**Issue by ice1000** [Hoverbear/getset#22]
https://github.com/Hoverbear/getset/blob/7b00ca8923a50cc7408f203a1111627ca71de526/src/lib.rs#L61

**Comment by Hoverbear** [comment]
How do you propose configuring it?

**Comment by ice1000** [comment]
It's a tough question indeed. Can we do `get_ = "pub"`?

**Comment by Hoverbear** [comment]
How about `#[get = "pub with-prefix"]`?

**Comment by ice1000** [comment]
LGTM!

**Comment by Hoverbear** [comment]
@ice1000 PTAL
