### ISSUE TITLE
copying/cloning getters?

### ISSUE THREAD

**Issue by Boscop** [Hoverbear/getset#3]
Are they possible with this crate, how?
E.g. if the field is a primitive type, I often want to copy it in the getter rather than return a ref.

**Comment by Boscop** [comment]
I'd appreciate it if copying getters could be added (with `#[inline(always)]`) :)
Even better would be if the derived getter (from the existing `#[get]` attrib) automatically copies the field when it has a primitive type.

**Comment by Hoverbear** [comment]
Hey! I'm sorry it took me so long to respond. I was moving! :astonished: 

I'm not sure I fully understand what you mean by a 'cloning getter', can't you just `x.get_y().clone()`?

**Comment by Boscop** [comment]
Yea, for `Copy` fields I could also just `*x.get_y()` but I meant, can it by default return the value directly instead of a reference, for fields that are `Copy`?

**Comment by Hoverbear** [comment]
Hmmm I'm not actually aware of a way to inspect the traits of a subject identity. (Eg I have no idea how to tell if `self.x: Copy`.) Are you aware of a way?

**Comment by Boscop** [comment]
So it could be made explicit by introducing another attribute that can be used like this:
```rust
#[clone = "pub"]
public: T,
```
Or `#[get_clone = "pub"]` if the `clone` attribute is not possible to use here.
It would clone the member and it would work for both `Copy` and `Clone` fields (assuming `.clone()` just copies, for types that impl both `Clone` and `Copy`).

**Comment by Hoverbear** [comment]
I feel like in this case just doing `get_y().clone()` in the calling code is more hygenic and makes the (possible) runtime cost explicit.

**Comment by Boscop** [comment]
In using getset for mostly Copy fields like bool, ints etc. and having to type `get_y().clone()` or `*get_y()` instead of just `get_y()` makes the code very ugly :/

**Comment by Hoverbear** [comment]
I understand and sympathize. I'm not really sure how to do it cleanly though. Maybe like a `get_y_cloned()`?

**Comment by Boscop** [comment]
The normal getter doesn't have 'get_' in the name (just `y()` and I would prefer the same for the cloning getter. 

The least verbose name would be `y_()` for the cloning getter (it's not uncommon to use names like that, e.g. the asprim crate uses `as_` because it's very short too)..

If the name of the cloning getter is any longer than 1 extra char, it'd be less chars to type `*foo.y()` which is ugly and the reason for introducing the cloning getter in the first place. 

And the cloning getters will almost exclusively be used with primitive `Copy` types, so they shouldn't have 'clone' in the name. They just clone to be more general (but actually copying getters would be enough for my use case).

But thinking about this more, when the type is a primitive, I'd actually prefer to have just one getter that copies. So I'd prefer to have an attribute like `#[get_ = "pub"]` and then it will only generate one getter but a cloning one!
Because for large non primitive fields I'd want to use the ref getter but for primitives I don't need the ref getter.

**Comment by Hoverbear** [comment]
Hmmm, what if we did like `#[get = "pub, clone"]` to signal the getter generated to clone?

**Comment by Boscop** [comment]
Or how about "*pub" (and "*" for non public) instead?  This alludes to `*foo.y()` so it's easy to remember and short to type :)

**Comment by Hoverbear** [comment]
I feel like this is not immediately obvious to a new user. Having `clone` in the syntax hints very strongly that something is being cloned and has a non-trivial runtime cost.

**Comment by Boscop** [comment]
Ok, let's backtrack here.. I don't even intend to ever use this on fields that aren't `Copy`, I was just using "cloning getters" because that would generalize it.
But thinking about this more, can't we just not clone, just copy?
So we'd have `#[get = "*"]`/`#[get = "*pub"]` for a dereferencing (copying) getter, and **no** way to generate a cloning getter, how about this? :)
This would be perfect, and can be used for all fields that are primitive numeric types.
In the rare cases where one would really want to clone, one could just do it manually with a ref-getter
So any `.clone()` would still be explicit.

**Comment by Proximyst** [comment]
I'd just like to propose using the `Deref` trait's function name `deref` as a suffix for the visibility instead; this would allow for `#[get = "deref"]` and `#[get = "pub_deref"]`, while the getter itself would still be the same, just returning a standard type (which again, RLS and IntelliJ Rust both support showing instead of the borrowed type).

**Comment by ice1000** [comment]
Yup I need this as well, let me take a look

**Comment by Hoverbear** [comment]
See #29
