### ISSUE TITLE
change attribute style

### ISSUE THREAD

**Issue by Luro02** [Hoverbear/getset#32]
I think it'd be better to have the attributes like this
```rust
#[derive(Getters, Setters, MutGetters)]
struct Hello {
    #[getter(cfgoption1, cfgoption2)]
    #[setter(cfgoption1, cfgoption2)]
    #[mutgetter(cfgoption1, cfgoption2)]
    value: String,
    #[setter(skip)]
    #[getter(skip)]
    #[mutgetter(skip)]
    skipme: (),
}
```
Essentially it'd be nice to have the same syntax, that [derive_builder](https://docs.rs/derive_builder/0.7.2/derive_builder/) has :)

---
It might be better to fuse them into a single trait
```rust
#[derive(GetSet)]
struct Hello {
    #[getset(get, set = "pub(crate)", get_mut = "pub")]
    value: String,
    #[getset(hidden)]
    skipme: ()
}
```

**Comment by Luro02** [comment]
related to #5

**Comment by Hoverbear** [comment]
This seems like two issues, the first being a breaking change that I see no motivation for, the second being a duplicate. Closing this. Thanks. :)
