### ISSUE TITLE
RFC: improve usability: serde like syntax 

### ISSUE THREAD

**Issue by Dushistov** [Hoverbear/getset#35]
It would be nice to have serde like syntax.
This make crate is more easy to use, because of many Rust users are already familiar with this syntax, or would be familiar in the near future. 

The raw idea:

```Rust
#[derive(Getset)]
#[getset(setters, getters)]
struct Foo {
#[getset(get_copy)]
f: i32,
#[getset(get_deref=&str)]
a: String,
#[getset(get_deref=&str)]
b: String,
#[getset(skip)]
c: usize,
}
```

**Comment by Hoverbear** [comment]
I think this would add a lot of complexity to the library and it'd be a major API break, so I suggest you implement it in a different crate (totally ok to fork this). :)

**Comment by Hoverbear** [comment]
Hi! We haven't seen activity on this in ~4 months so I'm closing this. :)
