### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by saschagrunert** [Hoverbear/getset#37]
Hey @Hoverbear :wave:, do you think it would be possible to release a new version which contains the latest features? Thank you in advance! :pray:

**Comment by Hoverbear** [comment]
Yeah! :)

**Comment by Hoverbear** [comment]
@saschagrunert 0.0.8 actually has all PRs merged in it, and it's available from https://crates.io/crates/getset already, can you help me understand what you're missing?

**Comment by Hoverbear** [comment]
Agh, no, you're right. We should have an 0.0.9 with #29. :)

**Comment by saschagrunert** [comment]
> Agh, no, you're right. We should have an 0.0.9 with #29. :)

Yes, that's the one I've been missing :+1:

**Comment by Hoverbear** [comment]
Great.  0.0.9 is released. :) Thanks for letting me know you needed this! https://crates.io/crates/getset/

**Comment by saschagrunert** [comment]
Thanks so much!
