### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by CreepySkeleton** [Hoverbear/getset#50]
For example, one of my previous PRs was broken 😢 and I didn't notice (yes, the master is broken, sorry). Continuous integration would allow you to catch such cases.

**Comment by Hoverbear** [comment]
Funny thing, I actually set up CI but seems I misconfigured it for PRs! https://github.com/Hoverbear/getset/actions

**Comment by Hoverbear** [comment]
I'm actually a bit annoyed, because it seems like Github Actions just plain out didn't work on that PR. You can see that https://github.com/Hoverbear/getset/runs/316680269 ran  the tests, so why didn't yours? #52 is an attempt to... fix... it?
