### ISSUE TITLE
Placing generated getters/setters into impl block?

### ISSUE THREAD

**Issue by Frederick888** [Hoverbear/getset#65]
First of all, thanks for maintaining such a handy crate!

Right now I'm trying to use it implement functions from traits, so I wonder whether it's possible to put the getters/setters into `impl` blocks? For example, I'd like to do:

```rust
trait HasFooSetter {
    fn some_fn_that_modifies_foo(&mut self) {
        self.set_foo("foo".to_owned());
    }
    fn set_foo(&mut self, foo: String) -> &mut Self;
}

#[derive(Setters)]
struct HasFoo {
    #[getset(set = "pub impl=HasFooSetter")]
    foo: String,
}

impl HasFooSetter for HasFoo {}
```

**Comment by Hoverbear** [comment]
I suggest implementing your own in this case! This crate already does too much, in my opinion. :)
